### ISSUE TITLE
Code about the t-SNE visualization section

### ISSUE THREAD

**Issue by Adherer** [jqnap/Twitter-Occupation-Prediction#1]
Hello, I read the paper you published at the ACL 2019 conference, I am very interested, and found your implementation code through github. When I reproduce your experiment, I found that t-SNE visualization is missing from your code. Because I am very interested in your work, and want to study your work well, if you are convenient, can you send me the code related to t-SNE visualization in your work? My mailbox is adherersun@163.com, I am grateful!

**Comment by Bhardwaj-Rishabh** [comment]
Hi! 
The t-SNE visualization can be done via [scikit-learn t-SNE](https://scikit-learn.org/stable/modules/generated/sklearn.manifold.TSNE.html). Save pre-final layer embedding and use t-SNE to reduce dimensions to two. Finally, plot users belonging to different classes with a different color. For any help in this regard, can directly ask us at rishabhbhardwaj15@gmail.com.
